export const defaultKeywords = [
    "malikgarments wholesale",
    "malik garments",
    "malik garments wholesale supplier",
    "wholesale garments supplier",
    "garment wholesaler india",
    "clothing wholesale supplier",
    "apparel wholesale india",
    "bulk garments supplier",
    "wholesale clothing for retailers",
    "garments manufacturer and wholesaler",
    "malikgarments",
    "malikgarments india",
    "malikgarments wholesale india",
    "malikgarments delhi",
    "malik garments manufacturer",
    "malik garments supplier india",
    "malik garments bulk order",
    "garments wholesale market",
    "clothing wholesale market india",
    "ready made garments wholesale",
    "mens garments wholesale",
    "womens garments wholesale",
    "kids garments wholesale",
    "all season garments wholesale",
    "bulk apparel supplier",
    "bulk clothing manufacturer",
    "low price garments wholesale",
    "factory price garments bulk",
    "direct manufacturer garments",
    "custom garments bulk order",
    "b2b garments supplier",
    "garments for resellers",
    "garments for distributors",
    "garments for shopkeepers",
    "retail garment supply",
    "online garments wholesale india",
    "wholesale garments website",
    "garments wholesale online",
    "bulk clothing order online",
    "wholesale fashion supplier",
    "malikgarments wholesale online",
    "malik garments b2b supplier",
    "malik garments wholesale india delhi",
    "trusted garment wholesaler india",
    "top garment wholesaler delhi",
    "best wholesale garments supplier",
    "wholesale clothing manufacturer",
    "bulk apparel manufacturer india",
    "ready made clothing wholesale supplier",
    "low cost garments wholesale",
    "premium quality garments wholesale",
    "export surplus garments wholesale",
    "mens wear wholesale supplier",
    "womens wear wholesale supplier",
    "kids wear wholesale supplier",
    "unisex garments wholesale",
    "seasonal garments wholesale",
    "winter wear wholesale supplier",
    "monsoon wear wholesale supplier",
    "sportswear wholesale supplier",
    "activewear wholesale supplier",
    "workwear wholesale supplier",
    "b2b clothing supplier india",
    "bulk clothing distributor",
    "bulk garment dealer india",
    "bulk apparel exporter india",
    "cheap wholesale garments india",
    "best price garments wholesale",
    "factory outlet garments wholesale",
    "garments supply for retailers",
    "garments supply for online sellers",
    "garments supply for resellers",
    "dropshipping garments supplier",
    "wholesale garments for ecommerce",
    "amazon flipkart sellers garments",
    "meesho sellers garments wholesale",
    "delhi garment wholesale market",
    "india garment wholesale hub",
    "pan india garment supply",
    "high margin garments wholesale",
    "profitable garments for resale",
    "fast selling garments wholesale"
];

export const categoryKeywords: Record<string, string[]> = {
    "jackets": [
        "wholesale jackets",
        "jackets wholesale supplier",
        "bulk jackets supplier",
        "winter jackets wholesale",
        "men jackets wholesale",
        "women jackets wholesale",
        "kids jackets wholesale",
        "waterproof jackets wholesale",
        "cheap jackets bulk",
        "jackets for resale",
        "wholesale jackets india",
        "wholesale jackets delhi",
        "buy jackets in bulk",
        "jacket manufacturer india",
        "jacket wholesaler india",
        "puffer jackets wholesale",
        "windcheater jackets wholesale",
        "bomber jackets wholesale",
        "hooded jackets wholesale",
        "sleeveless jackets wholesale",
        "polyester jackets wholesale",
        "cotton jackets wholesale",
        "export quality jackets wholesale",
        "jacket factory india",
        "jacket bulk manufacturer",
        "private label jackets wholesale",
        "custom jackets bulk order",
        "corporate jackets wholesale",
        "promotional jackets bulk",
        "industrial jackets wholesale",
        "safety jackets bulk supplier",
        "rainproof jackets wholesale",
        "cold storage jackets wholesale",
        "bulk order jackets india",
        "wholesale winter wear supplier"
    ],
    "rain suit": [
        "rain suit wholesale",
        "rain suits bulk supplier",
        "waterproof rain suit wholesale",
        "industrial rain suits wholesale",
        "reflective rain suit bulk",
        "rainwear wholesale supplier",
        "rain suit manufacturer india",
        "rain suit wholesale india",
        "rain suit wholesale delhi",
        "buy rain suits wholesale",
        "rainwear manufacturer india",
        "rainwear wholesaler india",
        "industrial rainwear wholesale",
        "bike rain suit wholesale",
        "two wheeler rain suit bulk",
        "monsoon rainwear wholesale",
        "commercial rainwear supplier",
        "rain suit factory india",
        "custom rain suits bulk",
        "corporate rain suits wholesale",
        "construction rain suit supplier",
        "delivery boy rain suit wholesale",
        "wholesale rainwear supplier",
        "monsoon wear wholesale supplier",
        "bulk order rainwear india"
    ],
    "rain coat": [
        "rain coat wholesale",
        "raincoats bulk supplier",
        "waterproof rain coat wholesale",
        "heavy duty raincoat bulk",
        "men raincoat wholesale",
        "women raincoat wholesale",
        "cheap raincoats bulk",
        "rain coat wholesale india",
        "raincoat supplier delhi",
        "buy raincoats bulk",
        "long raincoat wholesale",
        "short raincoat wholesale",
        "eva raincoat wholesale",
        "pvc raincoat wholesale",
        "nylon raincoat wholesale",
        "office raincoat bulk",
        "school raincoat wholesale",
        "raincoat factory india",
        "custom raincoats bulk order",
        "logo printed raincoats wholesale",
        "corporate raincoats supplier"
    ],
    "track suit": [
        "track suit wholesale",
        "tracksuits bulk supplier",
        "sports track suit wholesale",
        "gym track suits bulk",
        "men track suit wholesale",
        "women track suit wholesale",
        "kids tracksuits bulk",
        "polyester tracksuits wholesale",
        "track suit wholesale india",
        "track suit wholesaler delhi",
        "buy tracksuits wholesale",
        "wholesale sportswear supplier",
        "wholesale activewear india",
        "track suit manufacturer india",
        "sportswear manufacturer wholesale",
        "athletic tracksuits bulk",
        "running track suits wholesale",
        "training track suits bulk",
        "winter track suits wholesale",
        "summer track suits wholesale",
        "sports track suit manufacturer",
        "custom track suits bulk",
        "school track suits wholesale",
        "college track suits bulk supplier",
        "team track suits wholesale",
        "bulk order sportswear india"
    ],
    "lowers": [
        "lowers wholesale",
        "lowers bulk supplier",
        "track lowers wholesale",
        "joggers lowers wholesale",
        "sports lowers bulk",
        "men lowers wholesale",
        "gym lowers bulk supplier",
        "lowers wholesale india",
        "buy lowers bulk",
        "lower manufacturer india",
        "lower pant wholesaler",
        "track pants wholesale",
        "jogger pants wholesale",
        "gym lower bulk",
        "casual lower wholesale",
        "sports lower manufacturer",
        "wholesale fitness wear supplier",
        "wholesale sports clothing india",
        "wholesale workwear india",
        "wholesale outdoor clothing",
        "lower pant manufacturer india",
        "custom lowers bulk order",
        "printed lowers wholesale",
        "plain lowers wholesale",
        "school lowers bulk supplier"
    ]
};

export function getKeywordsForCategory(category: string): string[] {
    if (!category) return defaultKeywords;

    const normalizedCategory = category.toLowerCase().trim();

    // Try to find exact match or partial match in keys
    const matchedKey = Object.keys(categoryKeywords).find(key =>
        normalizedCategory.includes(key) || key.includes(normalizedCategory)
    );

    const specializedKeywords = matchedKey ? categoryKeywords[matchedKey] : [];

    // Combine specialized keywords with some general ones (first 10)
    return [...specializedKeywords, ...defaultKeywords.slice(0, 10)];
}

export function generateMetaKeywords(specificKeywords: string[] = []): string {
    // Combine specific keywords with default ones, remove duplicates
    const allKeywords = new Set([...specificKeywords, ...defaultKeywords]);
    return Array.from(allKeywords).join(', ');
}
